name:CI

on:
 push:

jobs:
  
  build:

       runs-on: ubuntu-latest

       steps:
       
         - name: Clonacion de codigo
           uses: actions/checkout@v4
           
         - name: Setup Java JDK
           uses: actions/setup-java@main
           with:
             java-version: '8'
             distribution: 'temurin'
             
         - name: Compilacion
           run: |
                 mvn package

         -name: Analisis SonarCloud
          run: |
            mvn clean verify sonar:sonar \
            -Dsonar.token=${{secrets.SONAR_TOKEN}} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=cmendo \
            -Dsonar.projectKey=cmendo_ms-aumento-voto
          
