#NAME: NOMBRE DEL PIPELINE
name: CI
#ON: PASO PARA CONFIGURACION DE TRIGGER O EVENTOS, LOS EVENTOS DISPONIBLE LOS CONSEGUIMOS COLCOANDO EN GOOGLE  
#EVENTS-THAT-TRIGGER-WORKFLOWS
on:
 push:    #PUSH: UNICO TRIGER O EVENTO CONFIGURADO EN ESTA PIPELINE
 
#JOBS: ES EL FLUJO DE TRABAJO, EL ORDEN EN QUE SE EJECUTAN LOS PASOS DE LA PIPELINE 
#OJO CON LA IDENTACION
jobs:
  #BUILD(Nombre del jobs, todo va identado para identificar las partes de la pipeline)
  #Una pipeline puede tener varios jobs:  
  build:
       #runs-on: son maquinas, bien sean fisicas o VM, onpremise o en la nube 
       #que van a ejecutar las instrucciones de la pipeline o las compilaciones
       #en github son runs-on, en jenkins y otras herramientas son agentes
       runs-on: ubuntu-latest
       #STEPS: PASOS A EJECUTAR DENTRO DEL JOBS, PUEDEN SER MAS DE UNO
       steps:

          - uses: actions/checkout@v3

          - name: Hola mundo
            run: |
              echo "Hola mundo"

          - name: Hola mundo 2
            run: |
              echo "Hola mundo 2"
           
         #actions/: son librerias para simplificar la construccion del codigo de la pipeline
         #- name: Clonacion de codigo
           #uses: actions/checkout@v4
           
         #- name: Setup Java JDK
           #uses: actions/setup-java@main
           #with:
            #java-version: '17'
             #java-version: '8'
             #distribution: 'temurin'
             
         #- name: Compilacion
           #run: |
                 #mvn package

         #- name: Analisis SonarCloud
          # run: |
           # mvn clean verify sonar:sonar \
           # -Dsonar.token=${{secrets.SONAR_TOKEN}} \
           # -Dsonar.host.url=https://sonarcloud.io \
           # -Dsonar.organization=cmendo \
           # -Dsonar.projectKey=cmendo_ms-aumento-voto
           
         #- name: Docker Login
           #uses: docker/login-action@v3.1.0
           #with:
             #username: cmendoza83
             #password: ${{ secrets.DOCKER_PASS }}
           
         #- name: Docker build
           #run:
                #docker build -t usach/ms-aumento-voto:lates .
          
         #- name: Docker push
           #run:
                  #docker push usach/ms-aumento-voto:lates
